# Generated by Django 5.1.6 on 2025-04-07 18:52

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('posicao', models.CharField(blank=True, max_length=50)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicial', models.DateField()),
                ('hora', models.TimeField(default='18:00:00')),
                ('local', models.CharField(max_length=100)),
                ('recorrente', models.BooleanField(default=False, verbose_name='Pelada semanal?')),
                ('dia_semana', models.CharField(blank=True, choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], max_length=1, null=True, verbose_name='Dia da semana')),
                ('semanas_duracao', models.PositiveIntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Número de semanas')),
                ('codigo_acesso', models.UUIDField(default=core.models.gerar_uuid, editable=False, unique=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelada')),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='peladas',
            field=models.ManyToManyField(related_name='jogadores', through='core.Presenca', to='core.pelada'),
        ),
    ]
