# Generated by Django 5.1.6 on 2025-04-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelada',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
