# Generated by Django 5.1.6 on 2025-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pelada_options_alter_presenca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelada',
            name='limite_participantes',
            field=models.IntegerField(default=20),
        ),
    ]
