# Generated by Django 5.1.6 on 2025-04-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pelada_limite_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='nivel_habilidade',
            field=models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], default=3, verbose_name='Nível de Habilidade'),
        ),
    ]
