# Generated by Django 5.1.6 on 2025-04-07 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pelada_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelada',
            name='data',
        ),
        migrations.AddField(
            model_name='pelada',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pelada',
            name='dia_semana',
            field=models.CharField(blank=True, choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], max_length=1, null=True, verbose_name='Dia da semana'),
        ),
        migrations.AddField(
            model_name='pelada',
            name='recorrente',
            field=models.BooleanField(default=False, verbose_name='Pelada semanal?'),
        ),
        migrations.AddField(
            model_name='pelada',
            name='semanas_duracao',
            field=models.PositiveIntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)], verbose_name='Número de semanas'),
        ),
    ]
