# Generated by Django 5.1.6 on 2025-04-07 00:07

from django.db import migrations
from django.utils import timezone

def set_default_dates(apps, schema_editor):
    Pelada = apps.get_model('core', 'Pelada')
    Pelada.objects.filter(data_inicial__isnull=True).update(
        data_inicial=timezone.now().date()
    )

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_remove_pelada_data_pelada_data_inicial_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_dates),
    ]
