# Generated by Django 5.1.6 on 2025-05-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presenca_nivel_habilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorteios', to='core.pelada')),
            ],
        ),
        migrations.CreateModel(
            name='SorteioTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('total_estrelas', models.PositiveIntegerField()),
                ('vagas', models.PositiveIntegerField()),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='core.sorteio')),
            ],
        ),
        migrations.CreateModel(
            name='SorteioJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_habilidade', models.PositiveIntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='core.sorteiotime')),
            ],
        ),
    ]
