# Generated by Django 5.1.6 on 2025-05-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_presenca_nivel_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_jogadores/'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='gols_marcados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='partidas_jogadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogador',
            name='vitorias',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
