# Generated by Django 5.1.6 on 2025-05-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jogador_foto_jogador_gols_marcados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='gols_marcados',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='partidas_jogadas',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='vitorias',
        ),
        migrations.AddField(
            model_name='jogador',
            name='perna_ruim',
            field=models.CharField(choices=[('D', 'Direita'), ('E', 'Esquerda'), ('A', 'Ambidestro')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(blank=True, choices=[('GK', 'Goleiro'), ('CB', 'Zagueiro'), ('LD', 'Lateral Direito'), ('LE', 'Lateral Esquerdo'), ('MC', 'Meia'), ('ATA', 'Atacante')], max_length=3),
        ),
    ]
