# Generated by Django 5.1.6 on 2025-04-07 00:08

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_set_default_data_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelada',
            name='data_inicial',
            field=models.DateField(),
        ),
    ]
