# Generated by Django 5.1.6 on 2025-05-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sorteio_sorteiotime_sorteiojogador'),
        ('core', '0006_remove_jogador_gols_marcados_and_more'),
    ]

    operations = [
    ]
