# Generated by Django 5.1.6 on 2025-04-07 13:14

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_make_data_inicial_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelada',
            name='codigo_acesso',
            field=models.UUIDField(blank=True, default=core.models.gerar_uuid, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
