# Generated by Django 5.1.6 on 2025-05-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250514_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogador',
            old_name='perna_ruim',
            new_name='perna_boa',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='foto',
        ),
    ]
