# Generated by Django 5.1.6 on 2025-04-07 13:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pelada_codigo_acesso_alter_jogador_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelada',
            name='codigo_acesso',
            field=models.UUIDField(default=core.models.gerar_uuid, editable=False, unique=True),
        ),
    ]
