# Generated by Django 5.1.6 on 2025-05-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_perna_ruim_jogador_perna_boa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(blank=True, choices=[('GOL', 'GOL'), ('DEF', 'Defensor'), ('MC', 'Meio Campista'), ('ATA', 'Atacante')], max_length=3),
        ),
    ]
