# Generated by Django 5.1.6 on 2025-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_jogador_posicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogador',
            name='email',
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(blank=True, choices=[('GOL', 'Goleiro'), ('DEF', 'Defensor'), ('MC', 'Meio Campista'), ('ATA', 'Atacante')], max_length=3),
        ),
    ]
