# Generated by Django 5.1.7 on 2025-04-22 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelada',
            options={'ordering': ['-data_inicial', 'hora']},
        ),
        migrations.AlterModelOptions(
            name='presenca',
            options={'ordering': ['pelada', 'jogador']},
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='peladas',
        ),
        migrations.RemoveField(
            model_name='pelada',
            name='dia_semana',
        ),
        migrations.RemoveField(
            model_name='pelada',
            name='semanas_duracao',
        ),
        migrations.AddField(
            model_name='presenca',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jogador',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pelada',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='pelada',
            name='local',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pelada',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pelada',
            name='organizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peladas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pelada',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together={('pelada', 'jogador')},
        ),
    ]
