name: CI/CD to Azure WebApp

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect static
        run: python manage.py collectstatic --noinput

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cypress & JS deps
        run: npm ci

      - name: Run migrations & start server
        run: |
          python manage.py migrate --noinput
          nohup gunicorn project.wsgi:application --bind 0.0.0.0:8000 &
        env:
          DJANGO_SETTINGS_MODULE: project.settings

      - name: Wait for server
        run: npx wait-on http://localhost:8000 --timeout 60000

      - name: Run Cypress E2E Tests
        run: npx cypress run --headless --config baseUrl=http://localhost:8000

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'futhub-webapp'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
